### ISSUE TITLE
How does "import Router from 'Router'" work?

### ISSUE THREAD

**Issue by msageryd** [exponentjs/rnplay#1]
Thank you very much for a great sample app. I haven't been able to get it up and running, but it's of great value to me to dig into the code.

I'm wondering what kind of magic you use to get this kind of statement work:

```
//main.js
import Router from 'Router';
```

No relative path and no npm package from what I can see. If the above do work, I have missed out on something important. I hate the relative paths in all of my imports.

**Comment by brentvatne** [comment]
hiya @michaelswe! this uses `@providesModule`, which is a not very well documented concept but that Facebook uses internally all over the place to make it easier to move files around

**Comment by sibelius** [comment]
@brentvatne I think u can close this

**Comment by msageryd** [comment]
I'll close it. Thanks.
